"""Add status and publish_date to Survey model

Revision ID: c1bbaaf318b8
Revises: 9968eac30af0
Create Date: 2025-08-23 19:37:34.240331

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'c1bbaaf318b8'
down_revision = '9968eac30af0'
branch_labels = None
depends_on = None


def upgrade():
 # Step 0: Create the ENUM type
    survey_status_enum = postgresql.ENUM('DRAFT', 'PUBLISHED', 'SCHEDULED', name='surveystatus', create_type=False)
    survey_status_enum.create(op.get_bind(), checkfirst=True)
    
    # Step 1: Add the new columns, making them nullable for now
    op.add_column('surveys', sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'SCHEDULED', name='surveystatus'), nullable=True))
    op.add_column('surveys', sa.Column('publish_date', sa.DateTime(), nullable=True))
    
    # Step 2: Update all existing rows with a default value for the new status column
    op.execute("UPDATE surveys SET status = 'DRAFT' WHERE status IS NULL")
    
    # Step 3: Now that all rows have a value, alter the column to be NOT NULL
    op.alter_column('surveys', 'status', nullable=False)
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('surveys', 'publish_date')
    op.drop_column('surveys', 'status')
    
    survey_status_enum = postgresql.ENUM('DRAFT', 'PUBLISHED', 'SCHEDULED', name='surveystatus', create_type=False)
    survey_status_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###

