"""Add is_external flag to Survey model

Revision ID: fa916c14a4c7
Revises: c1bbaaf318b8
Create Date: 2025-08-23 20:23:26.251917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa916c14a4c7'
down_revision = 'c1bbaaf318b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Add the new column, making it nullable for now
    op.add_column('surveys', sa.Column('is_external', sa.Boolean(), nullable=True))
    
    # Step 2: Update all existing rows with a default value of False
    op.execute("UPDATE surveys SET is_external = FALSE WHERE is_external IS NULL")
    
    # Step 3: Now that all rows have a value, alter the column to be NOT NULL
    op.alter_column('surveys', 'is_external', nullable=False)

    # ### end Alembic commands ###

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('surveys', 'is_external')

    # ### end Alembic commands ###
