/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SurveysCreateRouteImport } from './routes/surveys/create'
import { Route as SurveysLayoutRouteImport } from './routes/surveys/_layout'
import { Route as SurveysSurveyIdViewFormRouteImport } from './routes/surveys/$surveyId/viewForm'
import { Route as SurveysSurveyIdSubmissionsRouteImport } from './routes/surveys/$surveyId/submissions'
import { Route as SurveysSurveyIdPreviewRouteImport } from './routes/surveys/$surveyId/preview'
import { Route as SurveysSurveyIdEditRouteImport } from './routes/surveys/$surveyId/edit'

const SurveysRouteImport = createFileRoute('/surveys')()

const SurveysRoute = SurveysRouteImport.update({
  id: '/surveys',
  path: '/surveys',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SurveysCreateRoute = SurveysCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => SurveysRoute,
} as any)
const SurveysLayoutRoute = SurveysLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => SurveysRoute,
} as any)
const SurveysSurveyIdViewFormRoute = SurveysSurveyIdViewFormRouteImport.update({
  id: '/$surveyId/viewForm',
  path: '/$surveyId/viewForm',
  getParentRoute: () => SurveysRoute,
} as any)
const SurveysSurveyIdSubmissionsRoute =
  SurveysSurveyIdSubmissionsRouteImport.update({
    id: '/$surveyId/submissions',
    path: '/$surveyId/submissions',
    getParentRoute: () => SurveysRoute,
  } as any)
const SurveysSurveyIdPreviewRoute = SurveysSurveyIdPreviewRouteImport.update({
  id: '/$surveyId/preview',
  path: '/$surveyId/preview',
  getParentRoute: () => SurveysRoute,
} as any)
const SurveysSurveyIdEditRoute = SurveysSurveyIdEditRouteImport.update({
  id: '/$surveyId/edit',
  path: '/$surveyId/edit',
  getParentRoute: () => SurveysRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/surveys': typeof SurveysLayoutRoute
  '/surveys/create': typeof SurveysCreateRoute
  '/surveys/$surveyId/edit': typeof SurveysSurveyIdEditRoute
  '/surveys/$surveyId/preview': typeof SurveysSurveyIdPreviewRoute
  '/surveys/$surveyId/submissions': typeof SurveysSurveyIdSubmissionsRoute
  '/surveys/$surveyId/viewForm': typeof SurveysSurveyIdViewFormRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/surveys': typeof SurveysLayoutRoute
  '/surveys/create': typeof SurveysCreateRoute
  '/surveys/$surveyId/edit': typeof SurveysSurveyIdEditRoute
  '/surveys/$surveyId/preview': typeof SurveysSurveyIdPreviewRoute
  '/surveys/$surveyId/submissions': typeof SurveysSurveyIdSubmissionsRoute
  '/surveys/$surveyId/viewForm': typeof SurveysSurveyIdViewFormRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/surveys': typeof SurveysRouteWithChildren
  '/surveys/_layout': typeof SurveysLayoutRoute
  '/surveys/create': typeof SurveysCreateRoute
  '/surveys/$surveyId/edit': typeof SurveysSurveyIdEditRoute
  '/surveys/$surveyId/preview': typeof SurveysSurveyIdPreviewRoute
  '/surveys/$surveyId/submissions': typeof SurveysSurveyIdSubmissionsRoute
  '/surveys/$surveyId/viewForm': typeof SurveysSurveyIdViewFormRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/surveys'
    | '/surveys/create'
    | '/surveys/$surveyId/edit'
    | '/surveys/$surveyId/preview'
    | '/surveys/$surveyId/submissions'
    | '/surveys/$surveyId/viewForm'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/surveys'
    | '/surveys/create'
    | '/surveys/$surveyId/edit'
    | '/surveys/$surveyId/preview'
    | '/surveys/$surveyId/submissions'
    | '/surveys/$surveyId/viewForm'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/surveys'
    | '/surveys/_layout'
    | '/surveys/create'
    | '/surveys/$surveyId/edit'
    | '/surveys/$surveyId/preview'
    | '/surveys/$surveyId/submissions'
    | '/surveys/$surveyId/viewForm'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SurveysRoute: typeof SurveysRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/surveys': {
      id: '/surveys'
      path: '/surveys'
      fullPath: '/surveys'
      preLoaderRoute: typeof SurveysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surveys/create': {
      id: '/surveys/create'
      path: '/create'
      fullPath: '/surveys/create'
      preLoaderRoute: typeof SurveysCreateRouteImport
      parentRoute: typeof SurveysRoute
    }
    '/surveys/_layout': {
      id: '/surveys/_layout'
      path: '/surveys'
      fullPath: '/surveys'
      preLoaderRoute: typeof SurveysLayoutRouteImport
      parentRoute: typeof SurveysRoute
    }
    '/surveys/$surveyId/viewForm': {
      id: '/surveys/$surveyId/viewForm'
      path: '/$surveyId/viewForm'
      fullPath: '/surveys/$surveyId/viewForm'
      preLoaderRoute: typeof SurveysSurveyIdViewFormRouteImport
      parentRoute: typeof SurveysRoute
    }
    '/surveys/$surveyId/submissions': {
      id: '/surveys/$surveyId/submissions'
      path: '/$surveyId/submissions'
      fullPath: '/surveys/$surveyId/submissions'
      preLoaderRoute: typeof SurveysSurveyIdSubmissionsRouteImport
      parentRoute: typeof SurveysRoute
    }
    '/surveys/$surveyId/preview': {
      id: '/surveys/$surveyId/preview'
      path: '/$surveyId/preview'
      fullPath: '/surveys/$surveyId/preview'
      preLoaderRoute: typeof SurveysSurveyIdPreviewRouteImport
      parentRoute: typeof SurveysRoute
    }
    '/surveys/$surveyId/edit': {
      id: '/surveys/$surveyId/edit'
      path: '/$surveyId/edit'
      fullPath: '/surveys/$surveyId/edit'
      preLoaderRoute: typeof SurveysSurveyIdEditRouteImport
      parentRoute: typeof SurveysRoute
    }
  }
}

interface SurveysRouteChildren {
  SurveysLayoutRoute: typeof SurveysLayoutRoute
  SurveysCreateRoute: typeof SurveysCreateRoute
  SurveysSurveyIdEditRoute: typeof SurveysSurveyIdEditRoute
  SurveysSurveyIdPreviewRoute: typeof SurveysSurveyIdPreviewRoute
  SurveysSurveyIdSubmissionsRoute: typeof SurveysSurveyIdSubmissionsRoute
  SurveysSurveyIdViewFormRoute: typeof SurveysSurveyIdViewFormRoute
}

const SurveysRouteChildren: SurveysRouteChildren = {
  SurveysLayoutRoute: SurveysLayoutRoute,
  SurveysCreateRoute: SurveysCreateRoute,
  SurveysSurveyIdEditRoute: SurveysSurveyIdEditRoute,
  SurveysSurveyIdPreviewRoute: SurveysSurveyIdPreviewRoute,
  SurveysSurveyIdSubmissionsRoute: SurveysSurveyIdSubmissionsRoute,
  SurveysSurveyIdViewFormRoute: SurveysSurveyIdViewFormRoute,
}

const SurveysRouteWithChildren =
  SurveysRoute._addFileChildren(SurveysRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SurveysRoute: SurveysRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
